version: '3.2'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: mern-docker-project-server
    container_name: mern-docker-project-node-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env

    networks:
      - app-network

  mongo:
    image: mongo
  
    ports:
      - "27017:27017"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: mern-docker-project-client
    container_name: mern-docker-project-react-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network


networks:
    app-network:
        driver: bridge

